config/routes.rb
Randomfma::Application.routes.draw do
  get "tracks/show"

  root :to => "genre#index"

  resources :playlists
  resources :tracks

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base

  serialize :track_urls
  serialize :track_titles
  serialize :track_ids

  has_many :tracks
  FmaApiUrl = "http://freemusicarchive.org/api/get/tracks.xml"

  EmbedHtml = %(<object width="300" height="50"><param name="movie" value="http://freemusicarchive.org/swf/trackplayer.swf"/><param name="flashvars" value="track=http://freemusicarchive.org/services/playlists/embed/track/%s.xml"/><param name="allowscriptaccess" value="sameDomain"/><embed type="application/x-shockwave-flash" src="http://freemusicarchive.org/swf/trackplayer.swf" width="300" height="50" flashvars="track=http://freemusicarchive.org/services/playlists/embed/track/%s.xml" allowscriptaccess="sameDomain" /></object>) 


  def limit
    5
  end

  def generate
    num_pages = pages_for_genre
    page_numbers = []
    limit.times do
      page_numbers << rand(num_pages)
    end
    page_numbers.each do |num|  
      doc = xml_doc(tracks_xml(true, {:limit => 1, :page => num}))
      tracks << (Track.new(:url => doc.xpath("//track_url")[0].content,
                           :title => doc.xpath("//track_title")[0].content,
                           :artist_url => doc.xpath("//artist_url")[0].content,
                           :album_url => doc.xpath("//album_url")[0].content,
                           :album => doc.xpath("//album_title")[0].content,
                           :artist => doc.xpath("//artist_name")[0].content,
                           :fma_id => doc.xpath("//track_id")[0].content ))
    end
    save
  end

  def tracks_xml expire_cache, opts = {}
    if @tracks_xml.nil? || expire_cache  
      @tracks_xml = Curl::Easy.perform(api_url(opts)).body_str
    else
      @tracks_xml
    end
  end

  def xml_doc xmlstr
    @xml_doc = Nokogiri::XML(xmlstr)
  end

  def api_url opts = {}
    url = "#{FmaApiUrl}?genre_handle=#{genre_handle}"  
    opts.each {|k,v| url += "&#{k}=#{v}"}
    url
  end

  def pages_for_genre
    xml_doc(tracks_xml(true, {:limit => 1})).xpath("//total_pages")[0].content.to_i
  end

  def self.embedded_player_for_track(id)
    EmbedHtml % [id, id]
  end
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :playlist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/genre_controller.rb
class GenreController < ApplicationController
  Genres = ["Blues",
    "Classical",
    "Country",
    "Electronic",
    "Experimental",
    "Folk",
    "Hip-Hop",
    "International",
    "Jazz",
    "Novelty",
    "Old-Time / Historic",
    "Pop",
    "Rock",
    "Soul-R&B",
    "Spoken"]

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def show
    @pl = Playlist.find(params[:id])
  end

  def create
    @pl = Playlist.create :genre_handle => params[:genre_handle], :limit => params[:limit]
    @pl.generate 
    redirect_to(playlist_path(:id => @pl.id))
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def show
    @fma_track_id = params[:id] 
    @player_html = Playlist.embedded_player_for_track(@fma_track_id);
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fma_helper.rb
module FmaHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/fma/index.html.erb
<%= @curator_names.each do |cn|%>
  <p><%= cn.content %></p>
<%end%>

app/views/genre/_footer.html.haml
%p.footer! [Developed by James Hughes || #{link_to("github", "http://github.com/jpath")} || #{link_to("fma", "http://freemusicarchive.org/member/jpath")} || #{link_to("twitter", "http://twitter.com/#!/jpath29")}]

app/views/genre/index.html.erb
<%= Genres.each do |g| %>
<%end%>

app/views/genre/index.html.haml
#content
  %h1 RandomFMA - Five from the Archive
  %p!= "Select a genre from the list below, and let RandomFMA generate a playlist for you from the fabulous #{link_to('Free Music Archive!', 'http://freemusicarchive.org/', :class => 'orange_link')}. "
  #genre-list
    - GenreController::Genres.each do |g|
      %p= link_to g, playlists_path({:genre_handle => g}), {:method => "post"}
  %p (Coming soon...subgenres)
  = render 'footer'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Randomfma</title>
  <%= stylesheet_link_tag "randomfma.css"%>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/playlists/show.html.haml
#content
  %h1!= "Here is your randomly selected #{link_to(@pl.genre_handle, root_path, :title => "Switch Genre")} playlist from the #{link_to('Free Music Archive', 'http://freemusicarchive.org/')}:"
  #track-list
    - @pl.tracks.each do |t|
      %div
        #track-data
          %a(href="#{t.url}" class="track-link" id="track-link-#{t.fma_id}") 
            = t.title
          by 
          %a(href="#{t.artist_url}") 
            = t.artist
          from 
          %a(href="#{t.album_url}") 
            = t.album
        #track-player
          != Playlist.embedded_player_for_track(t.fma_id)
  #link-to-more
    = link_to "Get Five More", 
      playlists_path(:genre_handle => @pl.genre_handle), 
      {:method => "post"}
  = render 'genre/footer'

app/views/tracks/show.html.haml
!= @player_html